export const countryList = [
  { id: 'cn', name: 'China',                        hanzi: '中国',         pinyin: 'Zhōngguó',             flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/cn.svg' },
  { id: 'br', name: 'Brasil',                       hanzi: '巴西',         pinyin: 'Bāxī',                 flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/br.svg' },
  { id: 'us', name: 'Estados Unidos',               hanzi: '美国',         pinyin: 'Měiguó',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/us.svg' },
  { id: 'jp', name: 'Japão',                        hanzi: '日本',         pinyin: 'Rìběn',                flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/jp.svg' },
  { id: 'kr', name: 'Coreia do Sul',                hanzi: '韩国',         pinyin: 'Hánguó',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/kr.svg' },
  { id: 'in', name: 'Índia',                        hanzi: '印度',         pinyin: 'Yìndù',                flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/in.svg' },
  { id: 'ru', name: 'Rússia',                       hanzi: '俄罗斯',       pinyin: 'Éluósī',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ru.svg' },
  { id: 'de', name: 'Alemanha',                     hanzi: '德国',         pinyin: 'Déguó',                flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/de.svg' },
  { id: 'fr', name: 'França',                       hanzi: '法国',         pinyin: 'Fǎguó',                flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/fr.svg' },
  { id: 'gb', name: 'Reino Unido',                  hanzi: '英国',         pinyin: 'Yīngguó',              flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/gb.svg' },
  { id: 'it', name: 'Itália',                       hanzi: '意大利',       pinyin: 'Yìdàlì',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/it.svg' },
  { id: 'es', name: 'Espanha',                      hanzi: '西班牙',       pinyin: 'Xībānyá',              flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/es.svg' },
  { id: 'pt', name: 'Portugal',                     hanzi: '葡萄牙',       pinyin: 'Pútáoyá',              flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/pt.svg' },
  { id: 'mx', name: 'México',                       hanzi: '墨西哥',       pinyin: 'Mòxīgē',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/mx.svg' },
  { id: 'ar', name: 'Argentina',                    hanzi: '阿根廷',       pinyin: 'Āgēntíng',             flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ar.svg' },
  { id: 'ca', name: 'Canadá',                       hanzi: '加拿大',       pinyin: 'Jiānádà',              flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ca.svg' },
  { id: 'au', name: 'Austrália',                    hanzi: '澳大利亚',     pinyin: 'Àodàlìyà',             flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/au.svg' },
  { id: 'eg', name: 'Egito',                        hanzi: '埃及',         pinyin: 'Āijí',                 flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/eg.svg' },
  { id: 'za', name: 'África do Sul',                hanzi: '南非',         pinyin: 'Nánfēi',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/za.svg' },
  { id: 'id', name: 'Indonésia',                    hanzi: '印度尼西亚',   pinyin: 'Yìndùníxīyà',          flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/id.svg' },
  { id: 'cl', name: 'Chile',                        hanzi: '智利',         pinyin: 'Zhìlì',                flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/cl.svg' },
  { id: 'co', name: 'Colômbia',                     hanzi: '哥伦比亚',     pinyin: 'Gēlúnbǐyà',            flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/co.svg' },
  { id: 'pe', name: 'Peru',                         hanzi: '秘鲁',         pinyin: 'Bìlǔ',                 flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/pe.svg' },
  { id: 'uy', name: 'Uruguai',                      hanzi: '乌拉圭',       pinyin: 'Wūlāguī',              flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/uy.svg' },
  { id: 'py', name: 'Paraguai',                     hanzi: '巴拉圭',       pinyin: 'Bālāguī',              flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/py.svg' },
  { id: 'bo', name: 'Bolívia',                      hanzi: '玻利维亚',     pinyin: 'Bōlìwéiyà',            flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/bo.svg' },
  { id: 've', name: 'Venezuela',                    hanzi: '委内瑞拉',     pinyin: 'Wěinèiruìlā',          flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ve.svg' },
  { id: 'ec', name: 'Equador',                      hanzi: '厄瓜多尔',     pinyin: 'Èguāduō\'ěr',          flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ec.svg' },
  { id: 'cu', name: 'Cuba',                         hanzi: '古巴',         pinyin: 'Gǔbā',                 flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/cu.svg' },
  { id: 'pa', name: 'Panamá',                       hanzi: '巴拿马',       pinyin: 'Bānámǎ',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/pa.svg' },
  { id: 'th', name: 'Tailândia',                    hanzi: '泰国',         pinyin: 'Tàiguó',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/th.svg' },
  { id: 'vn', name: 'Vietnã',                       hanzi: '越南',         pinyin: 'Yuènán',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/vn.svg' },
  { id: 'ph', name: 'Filipinas',                    hanzi: '菲律宾',       pinyin: 'Fēilǜbīn',             flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ph.svg' },
  { id: 'my', name: 'Malásia',                      hanzi: '马来西亚',     pinyin: 'Mǎláixīyà',            flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/my.svg' },
  { id: 'sg', name: 'Singapura',                    hanzi: '新加坡',       pinyin: 'Xīnjiāpō',             flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/sg.svg' },
  { id: 'tr', name: 'Turquia',                      hanzi: '土耳其',       pinyin: 'Tǔ\'ěrqí',             flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/tr.svg' },
  { id: 'sa', name: 'Arábia Saudita',               hanzi: '沙特阿拉伯',   pinyin: 'Shātè Ālābó',          flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/sa.svg' },
  { id: 'ir', name: 'Irã',                          hanzi: '伊朗',         pinyin: 'Yīlǎng',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ir.svg' },
  { id: 'iq', name: 'Iraque',                       hanzi: '伊拉克',       pinyin: 'Yīlākè',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/iq.svg' },
  { id: 'il', name: 'Israel',                       hanzi: '以色列',       pinyin: 'Yǐsèliè',              flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/il.svg' },
  { id: 'no', name: 'Noruega',                      hanzi: '挪威',         pinyin: 'Nuówēi',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/no.svg' },
  { id: 'se', name: 'Suécia',                       hanzi: '瑞典',         pinyin: 'Ruìdiǎn',              flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/se.svg' },
  { id: 'fi', name: 'Finlândia',                    hanzi: '芬兰',         pinyin: 'Fēnlán',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/fi.svg' },
  { id: 'dk', name: 'Dinamarca',                    hanzi: '丹麦',         pinyin: 'Dānmài',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/dk.svg' },
  { id: 'nl', name: 'Holanda',                      hanzi: '荷兰',         pinyin: 'Hélán',                flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/nl.svg' },
  { id: 'be', name: 'Bélgica',                      hanzi: '比利时',       pinyin: 'Bǐlìshí',              flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/be.svg' },
  { id: 'ch', name: 'Suíça',                        hanzi: '瑞士',         pinyin: 'Ruìshì',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ch.svg' },
  { id: 'at', name: 'Áustria',                      hanzi: '奥地利',       pinyin: 'Àodìlì',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/at.svg' },
  { id: 'pl', name: 'Polônia',                      hanzi: '波兰',         pinyin: 'Bōlán',                flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/pl.svg' },
  { id: 'ua', name: 'Ucrânia',                      hanzi: '乌克兰',       pinyin: 'Wūkèlán',              flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ua.svg' },
  { id: 'gr', name: 'Grécia',                       hanzi: '希腊',         pinyin: 'Xīlà',                 flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/gr.svg' },
  { id: 'ie', name: 'Irlanda',                      hanzi: '爱尔兰',       pinyin: 'Ài\'ěrlán',            flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ie.svg' },
  { id: 'cz', name: 'República Tcheca',             hanzi: '捷克',         pinyin: 'Jiékè',                flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/cz.svg' },
  { id: 'hu', name: 'Hungria',                      hanzi: '匈牙利',       pinyin: 'Xiōngyálì',            flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/hu.svg' },
  { id: 'ro', name: 'Romênia',                      hanzi: '罗马尼亚',     pinyin: 'Luómǎníyà',            flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ro.svg' },
  { id: 'bg', name: 'Bulgária',                     hanzi: '保加利亚',     pinyin: 'Bǎojiālìyà',           flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/bg.svg' },
  { id: 'rs', name: 'Sérvia',                       hanzi: '塞尔维亚',     pinyin: 'Sài\'ěrwéiyà',         flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/rs.svg' },
  { id: 'hr', name: 'Croácia',                      hanzi: '克罗地亚',     pinyin: 'Kèluódìyà',            flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/hr.svg' },
  { id: 'ma', name: 'Marrocos',                     hanzi: '摩洛哥',       pinyin: 'Móluògē',              flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ma.svg' },
  { id: 'ng', name: 'Nigéria',                      hanzi: '尼日利亚',     pinyin: 'Nírìlìyà',             flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ng.svg' },
  { id: 'ke', name: 'Quênia',                       hanzi: '肯尼亚',       pinyin: 'Kěnníyà',              flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ke.svg' },
  { id: 'et', name: 'Etiópia',                      hanzi: '埃塞俄比亚',   pinyin: 'Āisài\'ébǐyà',         flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/et.svg' },
  { id: 'gh', name: 'Gana',                         hanzi: '加纳',         pinyin: 'Jiānà',                flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/gh.svg' },
  { id: 'ao', name: 'Angola',                       hanzi: '安哥拉',       pinyin: 'Āngēlā',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ao.svg' },
  { id: 'mz', name: 'Moçambique',                   hanzi: '莫桑比克',     pinyin: 'Mòsāngbǐkè',           flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/mz.svg' },
  { id: 'cv', name: 'Cabo Verde',                   hanzi: '佛得角',       pinyin: 'Fódéjiǎo',             flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/cv.svg' },
  { id: 'sn', name: 'Senegal',                      hanzi: '塞内加尔',     pinyin: 'Sàinèijiā\'ěr',        flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/sn.svg' },
  { id: 'dz', name: 'Argélia',                      hanzi: '阿尔及利亚',   pinyin: 'Ā\'ěrjílìyà',          flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/dz.svg' },
  { id: 'tn', name: 'Tunísia',                      hanzi: '突尼斯',       pinyin: 'Tūnísī',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/tn.svg' },
  { id: 'ly', name: 'Líbia',                        hanzi: '利比亚',       pinyin: 'Lìbǐyà',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ly.svg' },
  { id: 'cm', name: 'Camarões',                     hanzi: '喀麦隆',       pinyin: 'Kāmàilóng',            flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/cm.svg' },
  { id: 'ci', name: 'Costa do Marfim',              hanzi: '科特迪瓦',     pinyin: 'Kētèdíwǎ',             flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ci.svg' },
  { id: 'cd', name: 'Rep. Dem. do Congo',           hanzi: '刚果民主共和国', pinyin: 'Gāngguǒ Mínzhǔ Gònghéguó', flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/cd.svg' },
  { id: 'nz', name: 'Nova Zelândia',                hanzi: '新西兰',       pinyin: 'Xīnxīlán',             flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/nz.svg' },
  { id: 'fj', name: 'Fiji',                         hanzi: '斐济',         pinyin: 'Fěijì',                flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/fj.svg' },
  { id: 'pk', name: 'Paquistão',                    hanzi: '巴基斯坦',     pinyin: 'Bājīsītǎn',            flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/pk.svg' },
  { id: 'bd', name: 'Bangladesh',                   hanzi: '孟加拉国',     pinyin: 'Mèngjiālāguó',         flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/bd.svg' },
  { id: 'np', name: 'Nepal',                        hanzi: '尼泊尔',       pinyin: 'Níbó\'ěr',             flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/np.svg' },
  { id: 'lk', name: 'Sri Lanka',                    hanzi: '斯里兰卡',     pinyin: 'Sīlǐlánkǎ',            flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/lk.svg' },
  { id: 'af', name: 'Afeganistão',                  hanzi: '阿富汗',       pinyin: 'Āfùhàn',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/af.svg' },
  { id: 'kz', name: 'Cazaquistão',                  hanzi: '哈萨克斯坦',   pinyin: 'Hāsàkèsītǎn',          flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/kz.svg' },
  { id: 'uz', name: 'Uzbequistão',                  hanzi: '乌兹别克斯坦', pinyin: 'Wūzībiékèsītǎn',       flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/uz.svg' },
  { id: 'mn', name: 'Mongólia',                     hanzi: '蒙古',         pinyin: 'Měnggǔ',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/mn.svg' },
  { id: 'mm', name: 'Mianmar',                      hanzi: '缅甸',         pinyin: 'Miǎndiàn',             flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/mm.svg' },
  { id: 'la', name: 'Laos',                         hanzi: '老挝',         pinyin: 'Lǎowō',                flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/la.svg' },
  { id: 'kh', name: 'Camboja',                      hanzi: '柬埔寨',       pinyin: 'Jiǎnpǔzhài',           flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/kh.svg' },
  { id: 'sy', name: 'Síria',                        hanzi: '叙利亚',       pinyin: 'Xùlìyà',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/sy.svg' },
  { id: 'lb', name: 'Líbano',                       hanzi: '黎巴嫩',       pinyin: 'Líbānèn',              flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/lb.svg' },
  { id: 'jo', name: 'Jordânia',                     hanzi: '约旦',         pinyin: 'Yuēdàn',               flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/jo.svg' },
  { id: 'qa', name: 'Catar',                        hanzi: '卡塔尔',       pinyin: 'Kǎtǎ\'ěr',             flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/qa.svg' },
  { id: 'ae', name: 'Emirados Árabes Unidos',       hanzi: '阿联酋',       pinyin: 'Āliánqiú',             flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ae.svg' },
  { id: 'kw', name: 'Kuwait',                       hanzi: '科威特',       pinyin: 'Kēwēitè',              flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/kw.svg' },
  { id: 'om', name: 'Omã',                          hanzi: '阿曼',         pinyin: 'Āmàn',                 flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/om.svg' },
  { id: 'ye', name: 'Iêmen',                        hanzi: '也门',         pinyin: 'Yěmén',                flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ye.svg' },
  { id: 'ps', name: 'Palestina',                    hanzi: '巴勒斯坦',     pinyin: 'Bālèsītǎn',            flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ps.svg' },
  { id: 'am', name: 'Armênia',                      hanzi: '亚美尼亚',     pinyin: 'Yàměiníyà',            flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/am.svg' },
  { id: 'ge', name: 'Geórgia',                      hanzi: '格鲁吉亚',     pinyin: 'Gélǔjíyà',             flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ge.svg' },
  { id: 'az', name: 'Azerbaijão',                   hanzi: '阿塞拜疆',     pinyin: 'Āsàibàijiāng',         flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/az.svg' },
  { id: 'cy', name: 'Chipre',                       hanzi: '塞浦路斯',     pinyin: 'Sàipǔlùsī',            flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/cy.svg' },
  { id: 'mt', name: 'Malta',                        hanzi: '马耳他',       pinyin: 'Mǎ\'ěrtā',             flag: 'https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/mt.svg' },
];
