import { countryList } from './countries.js';

export const categories = [
  { id: 'all', label: 'Todos' },
  {
    id: 'pronome', label: 'Pronomes',
    guideTitle: 'Pronomes Pessoais e Demonstrativos',
    guideTip: '💡 <strong>Padrão visual:</strong> 我 (eu), 你 (você), 他 (ele) e 她 (ela) têm pinyin idêntico — <em>tā</em>. A diferença está no radical: 他 tem 亻(pessoa) e 她 tem 女 (mulher). Adicione 们 para pluralizar. Demonstrativos: 这 (este/próximo) ↔ 那 (aquele/distante).',
    guideLastCol: 'Dica mnemônica',
  },
  {
    id: 'verbo', label: 'Verbos',
    guideTitle: 'Verbos',
    guideTip: '💡 <strong>Verbos em chinês não conjugam.</strong> O mesmo caractere serve para todos os tempos e pessoas: 我说, 你说, 他说. O contexto e advérbios de tempo marcam quando a ação ocorre. 是 vs 叫: 是 identifica ("sou brasileiro"); 叫 é específico para nome ("me chamo João").',
    guideLastCol: 'Dica mnemônica',
  },
  {
    id: 'adverbio', label: 'Advérbios',
    guideTitle: 'Advérbios',
    guideTip: '💡 <strong>Advérbios sempre ficam antes do verbo ou adjetivo.</strong> Exemplo: 我也很高兴 — "eu também muito feliz" → "estou muito feliz também". 很 (hěn) é intensificador obrigatório com adjetivos: sem ele, a frase soa contrastiva.',
    guideLastCol: 'Exemplo rápido',
  },
  {
    id: 'particula', label: 'Partículas',
    guideTitle: 'Partículas Gramaticais',
    guideTip: '💡 <strong>Partículas são funcionais e sempre átonas.</strong> 吗 transforma qualquer afirmação em pergunta sim/não. 呢 pede confirmação ou continua o raciocínio. 的 liga modificador ao substantivo — indispensável para possessivos: 我的 (meu), 你的 (seu).',
    guideLastCol: 'Uso',
  },
  {
    id: 'substantivo', label: 'Substantivos',
    guideTitle: 'Substantivos',
    guideTip: '💡 <strong>Padrão de construção:</strong> [país] + 人 = nacionalidade | [país] + 语/文 = idioma. Substantivos em chinês não têm gênero gramatical — a distinção 男/女 é feita com adjetivos modificadores.',
    guideLastCol: 'Dica',
  },
  {
    id: 'adjetivo', label: 'Adjetivos',
    guideTitle: 'Adjetivos',
    guideTip: '💡 <strong>Adjetivos em chinês são predicados.</strong> Dispensam cópula: 她很漂亮 = "ela muito bonita" → "ela é muito bonita". 很 (hěn) precede o adjetivo na maioria dos casos — sem ele, a frase soa contrastiva ou enfática.',
    guideLastCol: 'Dica',
  },
  {
    id: 'numero', label: 'Números',
    guideTitle: 'Números',
    guideTip: '💡 <strong>Zero tem duas formas:</strong> 零 (líng) é o caractere formal; 〇 é a forma circular usada em datas, telefones e CEPs. Os dígitos de 1 a 9: 一二三四五六七八九; dezena: 十 (shí).',
    guideLastCol: 'Nota',
  },
  {
    id: 'lingua', label: 'Língua',
    guideTitle: 'Língua e Cultura',
    guideTip: '💡 <strong>语 vs 文:</strong> 语 enfatiza a língua <em>falada</em> (汉语 = mandarim oral); 文 abrange escrita, literatura e cultura (中文 = sistema escrito chinês). Na prática, para "falar português" diz-se 说葡萄牙语. 和 (hé) é a conjunção coordenativa mais básica.',
    guideLastCol: 'Dica',
  },
  {
    id: 'interrogativo', label: 'Interrogativos',
    guideTitle: 'Interrogativos',
    guideTip: '💡 <strong>什 e 么 raramente aparecem sozinhos.</strong> 什么 = "o quê?"; em composição: 为什么 (por quê?), 什么时候 (quando?). 哪 (qual/onde) forma 哪儿/哪里 (onde). 怎么样 avalia estado ou qualidade: "como está/é?".',
    guideLastCol: 'Contexto',
  },
  {
    id: 'nome-proprio', label: 'Nomes Próprios',
    guideTitle: 'Nomes Próprios e Lugares',
    guideTip: '💡 <strong>Transliterações fonéticas</strong> aproximam a pronúncia do idioma de origem: 里斯本 soa como "Lisboa"; 加拿大 soa como "Kanada". Alguns nomes combinam transliteração com significado: 东方 (oriente) é semântico.',
    guideLastCol: 'Origem',
  },
  { id: 'conectivo', label: 'Conectivos' },
  { id: 'pais', label: 'Países' },
];

export const hanziList = [

  // ── PRONOMES ──────────────────────────────────────────────────
  {
    id: 'wo',
    hanzi: '我', pinyin: 'wǒ', tone: 3,
    category: 'pronome', categoryLabel: 'Pronome · 3º tom',
    translation: 'eu, me, mim',
    fcTranslation: 'eu · me · mim',
    mnemonic: 'Imagine uma mão (手) apontando para si mesmo — é justamente o que "eu" faz.',
    examples: [{ zh: '我是巴西人。', pt: 'Sou brasileiro/a.' }],
  },
  {
    id: 'ni',
    hanzi: '你', pinyin: 'nǐ', tone: 3,
    category: 'pronome', categoryLabel: 'Pronome · 3º tom',
    translation: 'você',
    mnemonic: 'Radical 亻(pessoa) + 尔. Você é uma <em>pessoa</em> bem próxima de mim.',
    examples: [{ zh: '你好！', pt: 'Olá! (lit. você bem!)' }],
  },
  {
    id: 'nin',
    hanzi: '您', pinyin: 'nín', tone: 2,
    category: 'pronome', categoryLabel: 'Pronome formal · 2º tom',
    translation: 'o senhor / a senhora (formal)',
    fcTranslation: 'o senhor · a senhora',
    mnemonic: 'É 你 com um coração (心) embaixo — respeito que vem do coração.',
    examples: [{ zh: '您好！', pt: 'Olá (formal)' }],
  },
  {
    id: 'ta-m',
    hanzi: '他', pinyin: 'tā', tone: 1,
    category: 'pronome', categoryLabel: 'Pronome · 1º tom',
    translation: 'ele',
    mnemonic: 'Radical 亻(pessoa) + 也. Uma pessoa <em>também</em> presente = ele.',
    examples: [{ zh: '他是学生。', pt: 'Ele é estudante.' }],
  },
  {
    id: 'ta-f',
    hanzi: '她', pinyin: 'tā', tone: 1,
    category: 'pronome', categoryLabel: 'Pronome · 1º tom',
    translation: 'ela',
    mnemonic: 'Radical 女 (mulher) deixa clara a distinção de 他.',
    examples: [{ zh: '她也是学生。', pt: 'Ela também é estudante.' }],
  },
  {
    id: 'men',
    hanzi: '们', pinyin: 'men', tone: 0,
    category: 'pronome', categoryLabel: 'Sufixo · tom neutro',
    translation: 'sufixo de plural para pessoas',
    fcTranslation: 'sufixo de plural',
    mnemonic: 'Radical 亻(pessoa) + 门 (porta). Muitas pessoas passando pela mesma porta = plural.',
    examples: [{ zh: '我们 · 你们 · 他们', pt: '' }],
  },
  {
    id: 'zhe',
    hanzi: '这', pinyin: 'zhè', tone: 4,
    category: 'pronome', categoryLabel: 'Pronome demonstrativo · 4º tom',
    translation: 'este; esta; isto',
    fcTranslation: 'este · esta · isto',
    mnemonic: '这 (este/próximo) ↔ 那 (aquele/distante). Par fundamental dos demonstrativos.',
    examples: [{ zh: '这是我的朋友。', pt: 'Este/a é meu/minha amigo/a.' }],
  },
  {
    id: 'na-dem',
    hanzi: '那', pinyin: 'nà', tone: 4,
    category: 'pronome', categoryLabel: 'Pronome demonstrativo · 4º tom',
    translation: 'aquele; aquela; aquilo',
    fcTranslation: 'aquele · aquela · aquilo',
    mnemonic: '那 (aquele/distante) ↔ 这 (este/próximo). Par fundamental dos demonstrativos.',
    examples: [{ zh: '那是你的朋友吗？', pt: 'Aquele/a é seu/sua amigo/a?' }],
  },

  // ── VERBOS ────────────────────────────────────────────────────
  {
    id: 'shi',
    hanzi: '是', pinyin: 'shì', tone: 4,
    category: 'verbo', categoryLabel: 'Verbo · 4º tom',
    translation: 'ser; estar; é',
    fcTranslation: 'ser · estar · é',
    mnemonic: 'O radical 日 (sol) + 疋 — "o que é" está à luz do sol, exposto.',
    examples: [{ zh: '我是中国人。', pt: 'Sou chinês/a.' }],
  },
  {
    id: 'jiao',
    hanzi: '叫', pinyin: 'jiào', tone: 4,
    category: 'verbo', categoryLabel: 'Verbo · 4º tom',
    translation: 'chamar-se; chamar; gritar',
    fcTranslation: 'chamar-se · chamar',
    mnemonic: 'Radical 口 (boca) + 丩. Usar a boca para chamar alguém pelo nome.',
    examples: [{ zh: '我叫王芳。', pt: 'Me chamo Wang Fang.' }],
  },
  {
    id: 'shuo',
    hanzi: '说', pinyin: 'shuō', tone: 1,
    category: 'verbo', categoryLabel: 'Verbo · 1º tom',
    translation: 'falar; dizer',
    fcTranslation: 'falar · dizer',
    mnemonic: 'Radical 讠(fala) + 兑. O radical da fala é pista imediata: ação vocal.',
    examples: [{ zh: '你说中文吗？', pt: 'Você fala chinês?' }],
  },
  {
    id: 'renshi',
    hanzi: '认识', pinyin: 'rènshi', tone: 4,
    category: 'verbo', categoryLabel: 'Verbo · 4º/neutro tom',
    translation: 'conhecer (pessoa); reconhecer',
    fcTranslation: 'conhecer · reconhecer',
    mnemonic: '认 (reconhecer) + 识 (saber) — reconhecer e saber quem é a pessoa.',
    examples: [{ zh: '认识你很高兴。', pt: 'Prazer em conhecê-lo/a.' }],
  },
  {
    id: 'zai',
    hanzi: '在', pinyin: 'zài', tone: 4,
    category: 'verbo', categoryLabel: 'Verbo · 4º tom',
    translation: 'estar em; em; no/na',
    fcTranslation: 'estar em · em · no/na',
    mnemonic: 'Composto de 土 (terra) + 才 — estar firmemente situado num lugar.',
    examples: [{ zh: '你在哪儿工作？', pt: 'Onde você trabalha?' }],
  },
  {
    id: 'gongzuo',
    hanzi: '工作', pinyin: 'gōngzuò', tone: 1,
    category: 'verbo', categoryLabel: 'Verbo/Subst. · 1º/4º tom',
    translation: 'trabalhar; trabalho; emprego',
    fcTranslation: 'trabalhar · trabalho',
    mnemonic: '工 (ferramenta/trabalho) + 作 (fazer) — fazer trabalho.',
    examples: [{ zh: '你在哪儿工作？', pt: 'Onde você trabalha?' }],
  },
  {
    id: 'xuexi',
    hanzi: '学习', pinyin: 'xuéxí', tone: 2,
    category: 'verbo', categoryLabel: 'Verbo · 2º/2º tom',
    translation: 'estudar; aprender',
    fcTranslation: 'estudar · aprender',
    mnemonic: '学 (aprender) + 习 (praticar) — aprender e depois praticar.',
    examples: [{ zh: '你学习什么？', pt: 'O que você estuda?' }],
  },
  {
    id: 'keyi',
    hanzi: '可以', pinyin: 'kěyǐ', tone: 3,
    category: 'verbo', categoryLabel: 'Verbo modal · 3º/3º tom',
    translation: 'poder; ser permitido; pode',
    fcTranslation: 'poder · pode',
    mnemonic: 'Modal de permissão. 可以给我你的号码吗？— Pode me dar seu número?',
    examples: [{ zh: '可以给我你的号码吗？', pt: 'Pode me dar seu número?' }],
  },
  {
    id: 'gei',
    hanzi: '给', pinyin: 'gěi', tone: 3,
    category: 'verbo', categoryLabel: 'Verbo · 3º tom',
    translation: 'dar; para (destinatário)',
    fcTranslation: 'dar · para',
    mnemonic: 'Radical 糸 (fio) — ato de passar/entregar algo a alguém.',
    examples: [{ zh: '给我你的号码。', pt: 'Me dê seu número.' }],
  },
  {
    id: 'da-dianhua',
    hanzi: '打电话', pinyin: 'dǎ diànhuà', tone: 3,
    category: 'verbo', categoryLabel: 'Expressão verbal · 3º/4º/4º tom',
    translation: 'fazer uma ligação; telefonar',
    fcTranslation: 'telefonar · fazer ligação',
    mnemonic: '打 (fazer/bater) + 电话 (telefone) — "dar um toque no telefone".',
    examples: [{ zh: '我给你打电话。', pt: 'Eu te ligo.' }],
  },
  {
    id: 'fa',
    hanzi: '发', pinyin: 'fā', tone: 1,
    category: 'verbo', categoryLabel: 'Verbo · 1º tom',
    translation: 'enviar; emitir; mandar',
    fcTranslation: 'enviar · mandar',
    mnemonic: '发邮件 (enviar e-mail) · 发短信 (enviar mensagem) · 发音 (pronúncia).',
    examples: [{ zh: '我发电子邮件给你。', pt: 'Eu te mando um e-mail.' }],
  },
  {
    id: 'qing',
    hanzi: '请', pinyin: 'qǐng', tone: 3,
    category: 'verbo', categoryLabel: 'Verbo · 3º tom',
    translation: 'por favor; convidar; pedir',
    fcTranslation: 'por favor · convidar',
    mnemonic: 'Radical 讠(fala) — ato verbal de cortesia. 请进！请坐！',
    examples: [{ zh: '请进！请坐！', pt: 'Por favor entre! Por favor sente-se!' }],
  },
  {
    id: 'jin',
    hanzi: '进', pinyin: 'jìn', tone: 4,
    category: 'verbo', categoryLabel: 'Verbo · 4º tom',
    translation: 'entrar; avançar',
    fcTranslation: 'entrar · avançar',
    mnemonic: 'O verbo direcional de entrada. 请进！— Por favor, entre!',
    examples: [{ zh: '请进！', pt: 'Por favor, entre!' }],
  },
  {
    id: 'zuo',
    hanzi: '坐', pinyin: 'zuò', tone: 4,
    category: 'verbo', categoryLabel: 'Verbo · 4º tom',
    translation: 'sentar; tomar (transporte)',
    fcTranslation: 'sentar · tomar (ônibus, metrô)',
    mnemonic: 'Duas pessoas (人人) sobre o chão (土) — sentadas.',
    examples: [{ zh: '请坐！', pt: 'Por favor, sente-se!' }],
  },
  {
    id: 'xiexie',
    hanzi: '谢谢', pinyin: 'xièxie', tone: 4,
    category: 'verbo', categoryLabel: 'Expressão · 4º/neutro tom',
    translation: 'obrigado; obrigada; agradecer',
    fcTranslation: 'obrigado · obrigada',
    mnemonic: 'Radical 讠(fala) em 谢 — verbalizar gratidão. Reduplicação suaviza o tom.',
    examples: [{ zh: '谢谢你！', pt: 'Obrigado/a!' }],
  },
  {
    id: 'he-drink',
    hanzi: '喝', pinyin: 'hē', tone: 1,
    category: 'verbo', categoryLabel: 'Verbo · 1º tom',
    translation: 'beber; tomar (bebida)',
    mnemonic: 'Radical 口 (boca) — ação da boca. 喝茶 = tomar chá · 喝水 = beber água.',
    examples: [{ zh: '你喝茶吗？', pt: 'Você toma chá?' }],
  },
  {
    id: 'xihuan',
    hanzi: '喜欢', pinyin: 'xǐhuan', tone: 3,
    category: 'verbo', categoryLabel: 'Verbo · 3º/neutro tom',
    translation: 'gostar de; curtir; apreciar',
    fcTranslation: 'gostar · curtir',
    mnemonic: '喜 (alegria) + 欢 (entusiasmo) — dupla alegria = gostar muito.',
    examples: [{ zh: '你喜欢喝茶吗？', pt: 'Você gosta de chá?' }],
  },

  // ── ADVÉRBIOS ─────────────────────────────────────────────────
  {
    id: 'ye',
    hanzi: '也', pinyin: 'yě', tone: 3,
    category: 'adverbio', categoryLabel: 'Advérbio · 3º tom',
    translation: 'também',
    mnemonic: '我也是 — Eu também sou.',
    examples: [{ zh: '我也是学生。', pt: 'Eu também sou estudante.' }],
  },
  {
    id: 'dou',
    hanzi: '都', pinyin: 'dōu', tone: 1,
    category: 'adverbio', categoryLabel: 'Advérbio · 1º tom',
    translation: 'todos; ambos; tudo',
    fcTranslation: 'todos · ambos · tudo',
    mnemonic: '我们都是 — Nós todos somos.',
    examples: [{ zh: '我们都是学生。', pt: 'Somos todos estudantes.' }],
  },
  {
    id: 'zhi',
    hanzi: '只', pinyin: 'zhǐ', tone: 3,
    category: 'adverbio', categoryLabel: 'Advérbio · 3º tom',
    translation: 'só; apenas',
    fcTranslation: 'só · apenas',
    mnemonic: '我只说中文 — Eu só falo chinês.',
    examples: [{ zh: '我只说中文。', pt: 'Só falo chinês.' }],
  },
  {
    id: 'hai',
    hanzi: '还', pinyin: 'hái', tone: 2,
    category: 'adverbio', categoryLabel: 'Advérbio · 2º tom',
    translation: 'ainda; também (além disso)',
    fcTranslation: 'ainda · também (além disso)',
    mnemonic: '他还是学生 — Ele ainda é estudante.',
    examples: [{ zh: '他还是学生。', pt: 'Ele ainda é estudante.' }],
  },
  {
    id: 'bu',
    hanzi: '不', pinyin: 'bù', tone: 4,
    category: 'adverbio', categoryLabel: 'Negação · 4º / 2º tom',
    translation: 'não',
    mnemonic: '我不是 — Eu não sou. (Vira 2º tom antes de outro 4º tom: 不是 → bú shì)',
    examples: [{ zh: '我不是学生。', pt: 'Não sou estudante.' }],
  },
  {
    id: 'hen',
    hanzi: '很', pinyin: 'hěn', tone: 3,
    category: 'adverbio', categoryLabel: 'Advérbio · 3º tom',
    translation: 'muito; bem (intensificador)',
    fcTranslation: 'muito · bem',
    mnemonic: 'Quase sempre antes de adjetivos. Sem 很, a frase soa contrastiva: 他好 = "ele é bom (mas outros não são)".',
    examples: [{ zh: '我很好。', pt: 'Estou bem.' }],
  },

  // ── PARTÍCULAS ────────────────────────────────────────────────
  {
    id: 'ma',
    hanzi: '吗', pinyin: 'ma', tone: 0,
    category: 'particula', categoryLabel: 'Partícula · tom neutro',
    translation: 'partícula de pergunta sim/não',
    mnemonic: '你是学生吗？— Você é estudante?',
    examples: [{ zh: '你是学生吗？', pt: 'Você é estudante?' }],
  },
  {
    id: 'ne',
    hanzi: '呢', pinyin: 'ne', tone: 0,
    category: 'particula', categoryLabel: 'Partícula · tom neutro',
    translation: 'partícula de continuação/confirmação',
    fcTranslation: 'e você? · e quanto a...?',
    mnemonic: '你呢？— E você? / Que tal você?',
    examples: [{ zh: '你呢？', pt: 'E você?' }],
  },
  {
    id: 'de',
    hanzi: '的', pinyin: 'de', tone: 0,
    category: 'particula', categoryLabel: 'Partícula · tom neutro',
    translation: 'partícula atributiva (possessivo / modificador)',
    fcTranslation: 'partícula possessiva · atributiva',
    mnemonic: 'Sempre após o modificador: 我的 (meu) · 中国的 (chinês) · 漂亮的 (bonito).',
    examples: [{ zh: '我的电话号码 · 你的名字', pt: '' }],
  },

  // ── SUBSTANTIVOS ──────────────────────────────────────────────
  {
    id: 'xing',
    hanzi: '姓', pinyin: 'xìng', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º tom',
    translation: 'sobrenome; chamar-se (sobrenome)',
    fcTranslation: 'sobrenome',
    mnemonic: 'Radical 女 (mulher) + 生 (nascer). Sobrenome é o nome de nascença matrilinear.',
    examples: [{ zh: '您贵姓？', pt: 'Qual é seu sobrenome? (formal)' }],
  },
  {
    id: 'ming',
    hanzi: '名', pinyin: 'míng', tone: 2,
    category: 'substantivo', categoryLabel: 'Substantivo · 2º tom',
    translation: 'nome (dado); fama; famoso',
    fcTranslation: 'nome · fama',
    mnemonic: '夕 (noite) + 口 (boca). À noite, você grita um nome para identificar alguém no escuro.',
    examples: [{ zh: '你叫什么名字？', pt: 'Qual é seu nome?' }],
  },
  {
    id: 'zi',
    hanzi: '字', pinyin: 'zì', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º tom',
    translation: 'caractere; palavra escrita; nome de cortesia',
    fcTranslation: 'caractere · palavra escrita',
    mnemonic: '子 (filho) sob um teto 宀 = a escrita nasce e é abrigada.',
    examples: [{ zh: '汉字 (hànzì) = caracteres chineses', pt: '' }],
  },
  {
    id: 'guo',
    hanzi: '国', pinyin: 'guó', tone: 2,
    category: 'substantivo', categoryLabel: 'Substantivo · 2º tom',
    translation: 'país; nação',
    fcTranslation: 'país · nação',
    mnemonic: 'Um território (口 grande) guardado por fronteiras com jade (玉) no centro — o tesouro da nação.',
    examples: [{ zh: '中国 · 英国 · 美国 · 巴西', pt: '' }],
  },
  {
    id: 'gui',
    hanzi: '贵', pinyin: 'guì', tone: 4,
    category: 'substantivo', categoryLabel: 'Adjetivo/Subst. · 4º tom',
    translation: 'caro; nobre; honrado',
    fcTranslation: 'caro · nobre · honrado',
    mnemonic: '貝 (moeda antiga) embaixo = algo de alto valor monetário ou social.',
    examples: [{ zh: '贵姓 = honrado sobrenome (forma ultra-formal)', pt: '' }],
  },
  {
    id: 'jinchukou',
    hanzi: '进出口', pinyin: 'jìnchūkǒu', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º/1º/3º tom',
    translation: 'importação e exportação; comércio exterior',
    fcTranslation: 'importação e exportação',
    mnemonic: '进 (entrar) + 出 (sair) + 口 (porta) — entra e sai pela porta = comércio exterior.',
    examples: [{ zh: '进出口公司', pt: 'empresa de comércio exterior' }],
  },
  {
    id: 'jinkou',
    hanzi: '进口', pinyin: 'jìnkǒu', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º/3º tom',
    translation: 'importação; importar',
    mnemonic: '进 (entrar) + 口 (porta) = entrar pela porta = importar.',
    examples: [{ zh: '进口商品', pt: 'produto importado' }],
  },
  {
    id: 'chukou',
    hanzi: '出口', pinyin: 'chūkǒu', tone: 1,
    category: 'substantivo', categoryLabel: 'Substantivo · 1º/3º tom',
    translation: 'exportação; saída; exportar',
    fcTranslation: 'exportação · saída',
    mnemonic: '出 (sair) + 口 (porta) = sair pela porta = exportar.',
    examples: [{ zh: '出口产品', pt: 'produto de exportação' }],
  },
  {
    id: 'gongsi',
    hanzi: '公司', pinyin: 'gōngsī', tone: 1,
    category: 'substantivo', categoryLabel: 'Substantivo · 1º/1º tom',
    translation: 'empresa; companhia',
    mnemonic: '公 (coletivo) + 司 (administrar) = administração coletiva.',
    examples: [{ zh: '进出口公司', pt: 'empresa de comércio exterior' }],
  },
  {
    id: 'daxue',
    hanzi: '大学', pinyin: 'dàxué', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º/2º tom',
    translation: 'universidade; faculdade',
    mnemonic: '大 (grande) + 学 (aprender) = o grande lugar do saber.',
    examples: [{ zh: '里斯本大学', pt: 'Universidade de Lisboa' }],
  },
  {
    id: 'xi',
    hanzi: '系', pinyin: 'xì', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º tom',
    translation: 'departamento (acadêmico)',
    fcTranslation: 'departamento acadêmico',
    mnemonic: 'Originalmente "laço/elo" — grupo de estudiosos interligados.',
    examples: [{ zh: '文学系', pt: 'Departamento de Literatura' }],
  },
  {
    id: 'dianhua',
    hanzi: '电话', pinyin: 'diànhuà', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º/4º tom',
    translation: 'telefone; ligação',
    mnemonic: '电 (eletricidade) + 话 (fala) = fala elétrica.',
    examples: [{ zh: '你的电话号码是多少？', pt: 'Qual é seu número de telefone?' }],
  },
  {
    id: 'haoma',
    hanzi: '号码', pinyin: 'hàomǎ', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º/3º tom',
    translation: 'número (de telefone, código)',
    fcTranslation: 'número · código',
    mnemonic: '号 (número) + 码 (código) = código numérico.',
    examples: [{ zh: '电话号码', pt: 'número de telefone' }],
  },
  {
    id: 'dianziyoujian',
    hanzi: '电子邮件', pinyin: 'diànzǐ yóujiàn', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º/3º/2º/4º tom',
    translation: 'e-mail; correio eletrônico',
    fcTranslation: 'e-mail',
    mnemonic: '电子 (eletrônico) + 邮件 (correspondência) = correspondência eletrônica.',
    examples: [{ zh: '给我发电子邮件。', pt: 'Me mande um e-mail.' }],
  },
  {
    id: 'dianzi',
    hanzi: '电子', pinyin: 'diànzǐ', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º/3º tom',
    translation: 'eletrônico; elétron',
    mnemonic: '电 (eletricidade) + 子 (partícula) = elétron; como prefixo: eletrônico.',
    examples: [{ zh: '电子邮件 · 电子书', pt: 'e-mail · e-book' }],
  },
  {
    id: 'youjian',
    hanzi: '邮件', pinyin: 'yóujiàn', tone: 2,
    category: 'substantivo', categoryLabel: 'Substantivo · 2º/4º tom',
    translation: 'correspondência; carta; encomenda',
    fcTranslation: 'correspondência · carta',
    mnemonic: '邮 (correio) + 件 (item) = item de correio.',
    examples: [{ zh: '电子邮件', pt: 'e-mail (lit. correspondência eletrônica)' }],
  },
  {
    id: 'pengyou',
    hanzi: '朋友', pinyin: 'péngyou', tone: 2,
    category: 'substantivo', categoryLabel: 'Substantivo · 2º/neutro tom',
    translation: 'amigo; amiga',
    mnemonic: '朋 (dois grupos unidos) + 友 (amigo) = amizade verdadeira.',
    examples: [{ zh: '这是我的女朋友。', pt: 'Esta é minha namorada.' }],
  },
  {
    id: 'cha',
    hanzi: '茶', pinyin: 'chá', tone: 2,
    category: 'substantivo', categoryLabel: 'Substantivo · 2º tom',
    translation: 'chá',
    mnemonic: '艹 (planta) + 人 (pessoa) + 木 (árvore) — pessoa colhendo folhas de chá.',
    examples: [{ zh: '你喝茶吗？', pt: 'Você toma chá?' }],
  },
  {
    id: 'xueyuan',
    hanzi: '学院', pinyin: 'xuéyuàn', tone: 2,
    category: 'substantivo', categoryLabel: 'Substantivo · 2º/4º tom',
    translation: 'instituto; faculdade (divisão)',
    mnemonic: '学 (aprender) + 院 (recinto/pátio) = recinto do aprender.',
    examples: [{ zh: '东方学院', pt: 'Instituto de Estudos Orientais' }],
  },

  // ── ADJETIVOS ─────────────────────────────────────────────────
  {
    id: 'gaoxing',
    hanzi: '高兴', pinyin: 'gāoxìng', tone: 1,
    category: 'adjetivo', categoryLabel: 'Adjetivo · 1º/4º tom',
    translation: 'feliz; contente; alegre',
    fcTranslation: 'feliz · contente',
    mnemonic: '高 (alto) + 兴 (entusiasmo) = "alto entusiasmo" = felicidade.',
    examples: [{ zh: '认识你很高兴。', pt: 'Prazer em conhecê-lo/a.' }],
  },
  {
    id: 'da',
    hanzi: '大', pinyin: 'dà', tone: 4,
    category: 'adjetivo', categoryLabel: 'Adjetivo · 4º tom',
    translation: 'grande; muito (antes de substantivos)',
    fcTranslation: 'grande · muito',
    mnemonic: 'Pictograma de pessoa com braços abertos — bem grande! 大学 = universidade.',
    examples: [{ zh: '大学 · 大家', pt: 'universidade · todos' }],
  },
  {
    id: 'piaoliang',
    hanzi: '漂亮', pinyin: 'piàoliang', tone: 4,
    category: 'adjetivo', categoryLabel: 'Adjetivo · 4º/neutro tom',
    translation: 'bonito; bela; lindo',
    fcTranslation: 'bonito · bela · lindo',
    mnemonic: '氵(água) + 票 + 亮 (brilho) — brilho cintilante como reflexo na água.',
    examples: [{ zh: '你的朋友很漂亮！', pt: 'Sua amiga é muito bonita!' }],
  },
  {
    id: 'xiao',
    hanzi: '小', pinyin: 'xiǎo', tone: 3,
    category: 'adjetivo', categoryLabel: 'Adjetivo · 3º tom',
    translation: 'pequeno; jovem; pouco',
    mnemonic: 'Pictograma de algo dividido em partes miúdas. 小 ↔ 大 = pequeno ↔ grande.',
    examples: [{ zh: '小学 = escola primária (lit. pequeno aprender)', pt: '' }],
  },
  {
    id: 'nu',
    hanzi: '女', pinyin: 'nǚ', tone: 3,
    category: 'adjetivo', categoryLabel: 'Adjetivo/Subst. · 3º tom',
    translation: 'feminino; mulher; filha',
    fcTranslation: 'feminino · mulher',
    mnemonic: 'Pictograma de mulher sentada — um dos radicais mais antigos do chinês.',
    examples: [{ zh: '女朋友 (namorada) · 女学生 (aluna)', pt: '' }],
  },
  {
    id: 'nan',
    hanzi: '男', pinyin: 'nán', tone: 2,
    category: 'adjetivo', categoryLabel: 'Adjetivo/Subst. · 2º tom',
    translation: 'masculino; homem; filho',
    fcTranslation: 'masculino · homem',
    mnemonic: '田 (campo) + 力 (força) — força no campo = papel histórico do homem.',
    examples: [{ zh: '男朋友 (namorado) · 男学生 (aluno)', pt: '' }],
  },

  // ── NÚMEROS ───────────────────────────────────────────────────
  {
    id: 'ling',
    hanzi: '零 / 〇', pinyin: 'líng', tone: 2,
    category: 'numero', categoryLabel: 'Número · 2º tom',
    translation: 'zero',
    mnemonic: '零 = forma escrita formal; 〇 = forma circular usada em datas, telefones e CEPs.',
    examples: [{ zh: '电话: 零一零…', pt: 'Telefone: zero um zero…' }],
  },

  // ── LÍNGUA ────────────────────────────────────────────────────
  {
    id: 'yu',
    hanzi: '语', pinyin: 'yǔ', tone: 3,
    category: 'lingua', categoryLabel: 'Substantivo · 3º tom',
    translation: 'idioma; língua (falada)',
    fcTranslation: 'idioma · língua falada',
    mnemonic: 'Radical 讠(fala) — ênfase na oralidade. 英语, 汉语, 法语...',
    examples: [{ zh: '中文 / 汉语 · 英语 · 葡萄牙语', pt: '' }],
  },
  {
    id: 'wen',
    hanzi: '文', pinyin: 'wén', tone: 2,
    category: 'lingua', categoryLabel: 'Substantivo · 2º tom',
    translation: 'escrita; texto; língua; cultura',
    fcTranslation: 'escrita · texto · língua · cultura',
    mnemonic: 'Parece um ideograma de pessoa ornamentada com tatoo — cultura, arte, escrita.',
    examples: [{ zh: '中文 = chinês (língua/escrita)', pt: '' }],
  },
  {
    id: 'he',
    hanzi: '和', pinyin: 'hé', tone: 2,
    category: 'lingua', categoryLabel: 'Conjunção · 2º tom',
    translation: 'e; com; harmonia',
    fcTranslation: 'e · com · harmonia',
    mnemonic: '禾 (cereal) + 口 (boca). Compartilhar comida = harmonia, união, "e".',
    examples: [{ zh: '我和你 — Eu e você', pt: '' }],
  },

  // ── INTERROGATIVOS ────────────────────────────────────────────
  {
    id: 'na',
    hanzi: '哪', pinyin: 'nǎ', tone: 3,
    category: 'interrogativo', categoryLabel: 'Interrogativo · 3º tom',
    translation: 'qual; que; onde (em estruturas)',
    fcTranslation: 'qual · que · onde',
    mnemonic: 'Radical 口 (boca) — a boca fazendo a pergunta "qual?"',
    examples: [{ zh: '你是哪国人？', pt: 'De que país você é?' }],
  },
  {
    id: 'shen',
    hanzi: '什', pinyin: 'shén', tone: 2,
    category: 'interrogativo', categoryLabel: 'Interrogativo · 2º tom',
    translation: 'usado em 什么 (o quê?)',
    mnemonic: '你叫什么名字？— Qual é o seu nome?',
    examples: [{ zh: '什么 (shénme) = o quê? / qual?', pt: '' }],
  },
  {
    id: 'me',
    hanzi: '么', pinyin: 'me', tone: 0,
    category: 'interrogativo', categoryLabel: 'Partícula · tom neutro',
    translation: 'usado em 什么 (o quê?); 这么/那么 (assim/tão)',
    fcTranslation: 'usado em 什么 · 怎么 · 这么',
    mnemonic: 'Também em: 这么 (assim), 那么 (então/tão), 怎么 (como).',
    examples: [{ zh: '什么、这么、那么、怎么', pt: '' }],
  },
  {
    id: 'nar',
    hanzi: '哪儿 / 哪里', pinyin: 'nǎr / nǎli', tone: 3,
    category: 'interrogativo', categoryLabel: 'Interrogativo · 3º tom',
    translation: 'onde',
    mnemonic: '哪 + 儿/里 (sufixo de lugar). 哪儿 é mais comum em Pequim; 哪里 é padrão nacional.',
    examples: [{ zh: '你在哪儿工作？', pt: 'Onde você trabalha?' }],
  },
  {
    id: 'zenmeyang',
    hanzi: '怎么样', pinyin: 'zěnmeyàng', tone: 3,
    category: 'interrogativo', categoryLabel: 'Interrogativo · 3º/neutro/4º tom',
    translation: 'como está? o que acha? como é?',
    fcTranslation: 'como está? · o que acha?',
    mnemonic: '怎么 (como) + 样 (aparência/modo) = "de que tipo?" = como é/está?',
    examples: [{ zh: '你的工作怎么样？', pt: 'Como está seu trabalho?' }],
  },

  // ── NOMES PRÓPRIOS ────────────────────────────────────────────
  {
    id: 'lisbon-daxue',
    hanzi: '里斯本大学', pinyin: 'Lǐsīběn Dàxué', tone: 3,
    category: 'nome-proprio', categoryLabel: 'Nome próprio · 3º/1º/3º/4º/2º tom',
    translation: 'Universidade de Lisboa',
    mnemonic: '里斯本 = transliteração fonética de "Lisboa" + 大学 (universidade).',
    examples: [{ zh: '里斯本大学文学系', pt: 'Dep. de Letras da Univ. de Lisboa' }],
  },
  {
    id: 'wenxuexi',
    hanzi: '文学系', pinyin: 'Wénxuéxì', tone: 2,
    category: 'nome-proprio', categoryLabel: 'Nome próprio · 2º/2º/4º tom',
    translation: 'Departamento de Letras / Literatura',
    fcTranslation: 'Departamento de Letras',
    mnemonic: '文 (letras) + 学 (aprender) + 系 (departamento) = departamento de literatura.',
    examples: [{ zh: '里斯本大学文学系', pt: 'Dep. de Letras, Univ. de Lisboa' }],
  },
  {
    id: 'jianada',
    hanzi: '加拿大', pinyin: 'Jiānádà', tone: 1,
    category: 'nome-proprio', categoryLabel: 'Nome próprio · 1º/2º/4º tom',
    translation: 'Canadá',
    mnemonic: '加拿大 é transliteração fonética de "Canada" — sem significado intrínseco.',
    examples: [{ zh: '他是加拿大人。', pt: 'Ele é canadense.' }],
  },
  {
    id: 'dongfang-xueyuan',
    hanzi: '东方学院', pinyin: 'Dōngfāng Xuéyuàn', tone: 1,
    category: 'nome-proprio', categoryLabel: 'Nome próprio · 1º/1º/2º/4º tom',
    translation: 'Instituto de Estudos Orientais',
    mnemonic: '东方 (oriente, "direção leste") + 学院 (instituto) — nome semântico.',
    examples: [{ zh: '东方学院', pt: 'Instituto de Estudos Orientais' }],
  },

  // ── CARACTERES AVULSOS (componentes de nomes de países e vocabulário) ──
  // Substantivos
  {
    id: 'char-xi',
    hanzi: '西', pinyin: 'xī', tone: 1,
    category: 'substantivo', categoryLabel: 'Substantivo · 1º tom',
    translation: 'oeste; ocidente',
    fcTranslation: 'oeste · ocidente',
    mnemonic: 'Direção oeste. Aparece em 巴西 (Brasil) e 西班牙 (Espanha).',
    examples: [{ zh: '西方', pt: 'ocidente' }],
  },
  {
    id: 'char-ri',
    hanzi: '日', pinyin: 'rì', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º tom',
    translation: 'sol; dia',
    fcTranslation: 'sol · dia',
    mnemonic: 'Pictograma do sol. 日本 = "origem do sol" = Japão.',
    examples: [{ zh: '日本', pt: 'Japão' }],
  },
  {
    id: 'char-ben',
    hanzi: '本', pinyin: 'běn', tone: 3,
    category: 'substantivo', categoryLabel: 'Substantivo · 3º tom',
    translation: 'raiz; origem; (classificador de livros)',
    fcTranslation: 'raiz · origem',
    mnemonic: '木 (árvore) com um traço na base — a raiz. 日本 = origem do sol.',
    examples: [{ zh: '日本', pt: 'Japão' }],
  },
  {
    id: 'char-yin',
    hanzi: '印', pinyin: 'yìn', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º tom',
    translation: 'selo; carimbo; imprimir',
    fcTranslation: 'selo · carimbo',
    mnemonic: 'Carimbo que deixa marca. Aparece em 印度 (Índia).',
    examples: [{ zh: '印度', pt: 'Índia' }],
  },
  {
    id: 'char-du',
    hanzi: '度', pinyin: 'dù', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º tom',
    translation: 'grau; medida',
    fcTranslation: 'grau · medida',
    mnemonic: 'Unidade de medida (温度 temperatura). Aparece em 印度 (Índia).',
    examples: [{ zh: '印度', pt: 'Índia' }],
  },
  {
    id: 'char-ao',
    hanzi: '澳', pinyin: 'ào', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º tom',
    translation: 'enseada; baía',
    fcTranslation: 'enseada · baía',
    mnemonic: 'Radical 氵(água). 澳大利亚 (Austrália) e 澳门 (Macau).',
    examples: [{ zh: '澳大利亚', pt: 'Austrália' }],
  },
  {
    id: 'char-li',
    hanzi: '利', pinyin: 'lì', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º tom',
    translation: 'lucro; vantagem; afiado',
    fcTranslation: 'lucro · vantagem',
    mnemonic: '禾 (cereal) + 刂 (faca) — colher o lucro. Em 澳大利亚, 意大利.',
    examples: [{ zh: '利益', pt: 'benefício, interesse' }],
  },
  {
    id: 'char-ya',
    hanzi: '亚', pinyin: 'yà', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º tom',
    translation: 'Ásia; segundo; inferior',
    fcTranslation: 'Ásia · segundo',
    mnemonic: '亚洲 = Ásia. Aparece em 澳大利亚 (Austrália), 马来西亚 (Malásia).',
    examples: [{ zh: '亚洲', pt: 'Ásia' }],
  },
  {
    id: 'char-pu',
    hanzi: '葡', pinyin: 'pú', tone: 2,
    category: 'substantivo', categoryLabel: 'Substantivo · 2º tom',
    translation: 'uva (em 葡萄)',
    mnemonic: 'Radical 艹 (planta). Só aparece em 葡萄 (uva) e 葡萄牙 (Portugal).',
    examples: [{ zh: '葡萄牙', pt: 'Portugal' }],
  },
  {
    id: 'char-tao',
    hanzi: '萄', pinyin: 'táo', tone: 2,
    category: 'substantivo', categoryLabel: 'Substantivo · 2º tom',
    translation: 'uva (em 葡萄)',
    mnemonic: 'Radical 艹 (planta). Só aparece em 葡萄 (uva) e 葡萄牙 (Portugal).',
    examples: [{ zh: '葡萄', pt: 'uva' }],
  },
  {
    id: 'char-ya-tooth',
    hanzi: '牙', pinyin: 'yá', tone: 2,
    category: 'substantivo', categoryLabel: 'Substantivo · 2º tom',
    translation: 'dente',
    mnemonic: 'Pictograma de dentes. 葡萄牙 (Portugal), 西班牙 (Espanha).',
    examples: [{ zh: '葡萄牙', pt: 'Portugal' }],
  },
  {
    id: 'char-po',
    hanzi: '坡', pinyin: 'pō', tone: 1,
    category: 'substantivo', categoryLabel: 'Substantivo · 1º tom',
    translation: 'encosta; ladeira',
    fcTranslation: 'encosta · ladeira',
    mnemonic: '土 (terra) + 皮 (pele) — a superfície inclinada. 新加坡 (Singapura).',
    examples: [{ zh: '新加坡', pt: 'Singapura' }],
  },
  {
    id: 'char-lv',
    hanzi: '律', pinyin: 'lǜ', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º tom',
    translation: 'lei; regra',
    fcTranslation: 'lei · regra',
    mnemonic: '法律 = lei. Aparece em 菲律宾 (Filipinas).',
    examples: [{ zh: '法律', pt: 'lei' }],
  },
  {
    id: 'char-bin',
    hanzi: '宾', pinyin: 'bīn', tone: 1,
    category: 'substantivo', categoryLabel: 'Substantivo · 1º tom',
    translation: 'convidado; hóspede',
    fcTranslation: 'convidado · hóspede',
    mnemonic: '宾馆 = hotel. Aparece em 菲律宾 (Filipinas).',
    examples: [{ zh: '菲律宾', pt: 'Filipinas' }],
  },
  {
    id: 'char-ma',
    hanzi: '马', pinyin: 'mǎ', tone: 3,
    category: 'substantivo', categoryLabel: 'Substantivo · 3º tom',
    translation: 'cavalo',
    mnemonic: 'Pictograma de cavalo (forma simplificada). 马来西亚 (Malásia).',
    examples: [{ zh: '马来西亚', pt: 'Malásia' }],
  },
  {
    id: 'char-ge',
    hanzi: '哥', pinyin: 'gē', tone: 1,
    category: 'substantivo', categoryLabel: 'Substantivo · 1º tom',
    translation: 'irmão mais velho',
    fcTranslation: 'irmão mais velho',
    mnemonic: '哥哥 = irmão mais velho. Em 哥伦比亚 (Colômbia).',
    examples: [{ zh: '哥伦比亚', pt: 'Colômbia' }],
  },
  {
    id: 'char-lun',
    hanzi: '伦', pinyin: 'lún', tone: 2,
    category: 'substantivo', categoryLabel: 'Substantivo · 2º tom',
    translation: 'ordem moral; relações humanas',
    fcTranslation: 'ordem moral · ética',
    mnemonic: '伦理 = ética. Em 伦敦 (Londres), 哥伦比亚 (Colômbia).',
    examples: [{ zh: '哥伦比亚', pt: 'Colômbia' }],
  },
  {
    id: 'char-gen',
    hanzi: '根', pinyin: 'gēn', tone: 1,
    category: 'substantivo', categoryLabel: 'Substantivo · 1º tom',
    translation: 'raiz; (classificador de objetos longos)',
    fcTranslation: 'raiz',
    mnemonic: '木 (árvore) + 艮 — a raiz da árvore. Em 阿根廷 (Argentina).',
    examples: [{ zh: '阿根廷', pt: 'Argentina' }],
  },
  {
    id: 'char-ting',
    hanzi: '廷', pinyin: 'tíng', tone: 2,
    category: 'substantivo', categoryLabel: 'Substantivo · 2º tom',
    translation: 'corte real; tribunal',
    fcTranslation: 'corte real',
    mnemonic: '宫廷 = palácio real. Em 阿根廷 (Argentina).',
    examples: [{ zh: '阿根廷', pt: 'Argentina' }],
  },
  {
    id: 'char-nei',
    hanzi: '内', pinyin: 'nèi', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º tom',
    translation: 'dentro; interior',
    fcTranslation: 'dentro · interior',
    mnemonic: '国内 = nacional (dentro do país). Em 委内瑞拉 (Venezuela).',
    examples: [{ zh: '国内', pt: 'nacional, doméstico' }],
  },
  {
    id: 'char-sha',
    hanzi: '沙', pinyin: 'shā', tone: 1,
    category: 'substantivo', categoryLabel: 'Substantivo · 1º tom',
    translation: 'areia',
    mnemonic: '氵(água) + 少 (pouco) — onde há pouca água, areia. 沙特 (Arábia Saudita).',
    examples: [{ zh: '沙特阿拉伯', pt: 'Arábia Saudita' }],
  },
  {
    id: 'char-bo',
    hanzi: '伯', pinyin: 'bó', tone: 2,
    category: 'substantivo', categoryLabel: 'Substantivo · 2º tom',
    translation: 'tio (irmão mais velho do pai)',
    fcTranslation: 'tio paterno mais velho',
    mnemonic: '伯父 = tio paterno. Em 阿拉伯 (árabe), 沙特阿拉伯.',
    examples: [{ zh: '阿拉伯', pt: 'árabe / Arábia' }],
  },
  {
    id: 'char-se',
    hanzi: '色', pinyin: 'sè', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º tom',
    translation: 'cor',
    mnemonic: '颜色 = cor. Em 以色列 (Israel).',
    examples: [{ zh: '以色列', pt: 'Israel' }],
  },
  {
    id: 'char-yang',
    hanzi: '样', pinyin: 'yàng', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º tom',
    translation: 'aparência; modo; tipo',
    fcTranslation: 'aparência · tipo',
    mnemonic: '一样 = igual; 怎么样 = como está? (de que modo?).',
    examples: [{ zh: '怎么样？', pt: 'Como está? / O que acha?' }],
  },
  {
    id: 'char-er',
    hanzi: '儿', pinyin: 'ér', tone: 2,
    category: 'substantivo', categoryLabel: 'Substantivo · 2º tom',
    translation: 'criança; filho; (sufixo retroflexo)',
    fcTranslation: 'criança · filho',
    mnemonic: '儿子 = filho. Também sufixo: 哪儿 (onde), 这儿 (aqui).',
    examples: [{ zh: '哪儿', pt: 'onde' }],
  },
  {
    id: 'char-yuan',
    hanzi: '院', pinyin: 'yuàn', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º tom',
    translation: 'pátio; recinto; instituição',
    fcTranslation: 'pátio · instituição',
    mnemonic: '学院 = instituto; 医院 = hospital; 电影院 = cinema.',
    examples: [{ zh: '医院', pt: 'hospital' }],
  },

  // Adjetivos
  {
    id: 'char-mei',
    hanzi: '美', pinyin: 'měi', tone: 3,
    category: 'adjetivo', categoryLabel: 'Adjetivo · 3º tom',
    translation: 'belo; bonito; (abrev. América/EUA)',
    fcTranslation: 'belo · bonito',
    mnemonic: '美丽 = belo. 美国 = EUA ("país belo").',
    examples: [{ zh: '美国', pt: 'Estados Unidos' }],
  },
  {
    id: 'char-xin',
    hanzi: '新', pinyin: 'xīn', tone: 1,
    category: 'adjetivo', categoryLabel: 'Adjetivo · 1º tom',
    translation: 'novo',
    mnemonic: '新闻 = notícias (coisas novas). 新加坡 = Singapura.',
    examples: [{ zh: '新加坡', pt: 'Singapura' }],
  },
  {
    id: 'char-wu',
    hanzi: '乌', pinyin: 'wū', tone: 1,
    category: 'adjetivo', categoryLabel: 'Adjetivo · 1º tom',
    translation: 'preto; escuro; corvo',
    fcTranslation: 'preto · escuro',
    mnemonic: '乌云 = nuvem escura. Em 乌拉圭 (Uruguai), 乌兹别克斯坦.',
    examples: [{ zh: '乌拉圭', pt: 'Uruguai' }],
  },
  {
    id: 'char-rui',
    hanzi: '瑞', pinyin: 'ruì', tone: 4,
    category: 'adjetivo', categoryLabel: 'Adjetivo · 4º tom',
    translation: 'auspicioso; de bom augúrio',
    fcTranslation: 'auspicioso',
    mnemonic: '瑞雪 = neve auspiciosa. Em 委内瑞拉 (Venezuela), 瑞士 (Suíça).',
    examples: [{ zh: '委内瑞拉', pt: 'Venezuela' }],
  },
  {
    id: 'char-te',
    hanzi: '特', pinyin: 'tè', tone: 4,
    category: 'adjetivo', categoryLabel: 'Adjetivo · 4º tom',
    translation: 'especial; particular',
    fcTranslation: 'especial · particular',
    mnemonic: '特别 = especialmente. Em 沙特 (Arábia Saudita).',
    examples: [{ zh: '特别', pt: 'especial, especialmente' }],
  },
  {
    id: 'char-tan',
    hanzi: '坦', pinyin: 'tǎn', tone: 3,
    category: 'adjetivo', categoryLabel: 'Adjetivo · 3º tom',
    translation: 'plano; nivelado; franco',
    fcTranslation: 'plano · franco',
    mnemonic: '平坦 = plano; 坦白 = franco. Em 哈萨克斯坦 (Cazaquistão).',
    examples: [{ zh: '哈萨克斯坦', pt: 'Cazaquistão' }],
  },

  // Verbos
  {
    id: 'char-jia',
    hanzi: '加', pinyin: 'jiā', tone: 1,
    category: 'verbo', categoryLabel: 'Verbo · 1º tom',
    translation: 'adicionar; somar',
    fcTranslation: 'adicionar · somar',
    mnemonic: '力 (força) + 口 — somar esforço. Em 加拿大 (Canadá), 新加坡.',
    examples: [{ zh: '加拿大', pt: 'Canadá' }],
  },
  {
    id: 'char-na',
    hanzi: '拿', pinyin: 'ná', tone: 2,
    category: 'verbo', categoryLabel: 'Verbo · 2º tom',
    translation: 'pegar; segurar',
    fcTranslation: 'pegar · segurar',
    mnemonic: '合 (juntar) + 手 (mão) — juntar na mão = pegar. Em 加拿大 (Canadá).',
    examples: [{ zh: '加拿大', pt: 'Canadá' }],
  },
  {
    id: 'char-lai',
    hanzi: '来', pinyin: 'lái', tone: 2,
    category: 'verbo', categoryLabel: 'Verbo · 2º tom',
    translation: 'vir',
    mnemonic: 'Verbo direcional de aproximação. Em 马来西亚 (Malásia).',
    examples: [{ zh: '马来西亚', pt: 'Malásia' }],
  },
  {
    id: 'char-la',
    hanzi: '拉', pinyin: 'lā', tone: 1,
    category: 'verbo', categoryLabel: 'Verbo · 1º tom',
    translation: 'puxar',
    mnemonic: '扌(mão) + 立 (de pé) — puxar com a mão. Em 委内瑞拉, 阿拉伯.',
    examples: [{ zh: '委内瑞拉', pt: 'Venezuela' }],
  },
  {
    id: 'char-bi',
    hanzi: '比', pinyin: 'bǐ', tone: 3,
    category: 'verbo', categoryLabel: 'Verbo · 3º tom',
    translation: 'comparar; do que (comparação)',
    fcTranslation: 'comparar',
    mnemonic: '比较 = comparar. Em 哥伦比亚 (Colômbia).',
    examples: [{ zh: '哥伦比亚', pt: 'Colômbia' }],
  },
  {
    id: 'char-luo',
    hanzi: '罗', pinyin: 'luó', tone: 2,
    category: 'verbo', categoryLabel: 'Verbo · 2º tom',
    translation: 'reunir; recolher; rede',
    fcTranslation: 'reunir · recolher',
    mnemonic: '罗马 = Roma. Em 俄罗斯 (Rússia).',
    examples: [{ zh: '俄罗斯', pt: 'Rússia' }],
  },
  {
    id: 'char-ke',
    hanzi: '克', pinyin: 'kè', tone: 4,
    category: 'verbo', categoryLabel: 'Verbo · 4º tom',
    translation: 'vencer; superar; grama (g)',
    fcTranslation: 'vencer · superar',
    mnemonic: '克服 = superar. Em 伊拉克 (Iraque), 哈萨克斯坦.',
    examples: [{ zh: '伊拉克', pt: 'Iraque' }],
  },
  {
    id: 'char-lie',
    hanzi: '列', pinyin: 'liè', tone: 4,
    category: 'verbo', categoryLabel: 'Verbo · 4º tom',
    translation: 'enfileirar; alinhar; fila',
    fcTranslation: 'enfileirar · fila',
    mnemonic: '列车 = trem (vagões em fila). Em 以色列 (Israel).',
    examples: [{ zh: '以色列', pt: 'Israel' }],
  },
  {
    id: 'char-wei',
    hanzi: '委', pinyin: 'wěi', tone: 3,
    category: 'verbo', categoryLabel: 'Verbo · 3º tom',
    translation: 'confiar; delegar; encarregar',
    fcTranslation: 'confiar · delegar',
    mnemonic: '委托 = confiar uma tarefa. Em 委内瑞拉 (Venezuela).',
    examples: [{ zh: '委内瑞拉', pt: 'Venezuela' }],
  },

  // Advérbio
  {
    id: 'char-bie',
    hanzi: '别', pinyin: 'bié', tone: 2,
    category: 'adverbio', categoryLabel: 'Advérbio · 2º tom',
    translation: 'não (proibição); separar; outro',
    fcTranslation: 'não (proibição) · outro',
    mnemonic: '别说话！= Não fale! Em 乌兹别克斯坦 (Uzbequistão).',
    examples: [{ zh: '别走', pt: 'Não vá' }],
  },

  // Interrogativo
  {
    id: 'char-zen',
    hanzi: '怎', pinyin: 'zěn', tone: 3,
    category: 'interrogativo', categoryLabel: 'Interrogativo · 3º tom',
    translation: 'como (em 怎么 / 怎样)',
    fcTranslation: 'como',
    mnemonic: '怎么 = como?; 怎么样 = como está? Raramente aparece sozinho.',
    examples: [{ zh: '怎么样？', pt: 'Como está? / O que acha?' }],
  },

  // Língua e cultura
  {
    id: 'char-han-chinese',
    hanzi: '汉', pinyin: 'hàn', tone: 4,
    category: 'lingua', categoryLabel: 'Substantivo · 4º tom',
    translation: 'Han (etnia chinesa); chinês',
    fcTranslation: 'Han · chinês',
    mnemonic: '汉语 = mandarim (língua Han); 汉字 = caracteres chineses.',
    examples: [{ zh: '汉语', pt: 'língua chinesa (mandarim)' }],
  },

  // Partículas / preposições
  {
    id: 'char-yi',
    hanzi: '以', pinyin: 'yǐ', tone: 3,
    category: 'particula', categoryLabel: 'Preposição · 3º tom',
    translation: 'por meio de; com; usar',
    fcTranslation: 'por meio de · com',
    mnemonic: '以前 = antes; 可以 = poder. Em 以色列 (Israel).',
    examples: [{ zh: '以前', pt: 'antes, no passado' }],
  },
  {
    id: 'char-ha',
    hanzi: '哈', pinyin: 'hā', tone: 1,
    category: 'particula', categoryLabel: 'Interjeição · 1º tom',
    translation: '(riso) ha!; exalar',
    fcTranslation: '(riso) ha!',
    mnemonic: '哈哈 = haha. Em 哈萨克斯坦 (Cazaquistão).',
    examples: [{ zh: '哈哈', pt: 'haha (riso)' }],
  },

  // Nomes próprios / caracteres fonéticos de transliteração
  {
    id: 'char-ba',
    hanzi: '巴', pinyin: 'bā', tone: 1,
    category: 'nome-proprio', categoryLabel: 'Caractere fonético · 1º tom',
    translation: '(fonético) em 巴西 (Brasil); ansiar; agarrar-se',
    fcTranslation: '(fon.) em 巴西',
    mnemonic: 'Som "ba" em transliterações: 巴西 (Brasil), 古巴 (Cuba).',
    examples: [{ zh: '巴西', pt: 'Brasil' }],
  },
  {
    id: 'char-han',
    hanzi: '韩', pinyin: 'hán', tone: 2,
    category: 'nome-proprio', categoryLabel: 'Nome próprio · 2º tom',
    translation: 'Coreia (韩国); sobrenome Han',
    fcTranslation: 'Coreia · sobrenome Han',
    mnemonic: '韩国 = Coreia do Sul; 韩语 = coreano.',
    examples: [{ zh: '韩国', pt: 'Coreia do Sul' }],
  },
  {
    id: 'char-fei',
    hanzi: '菲', pinyin: 'fēi', tone: 1,
    category: 'nome-proprio', categoryLabel: 'Caractere fonético · 1º tom',
    translation: '(fonético) em 菲律宾 (Filipinas); fragrante',
    fcTranslation: '(fon.) em 菲律宾',
    mnemonic: 'Som "fei" em 菲律宾 (Filipinas).',
    examples: [{ zh: '菲律宾', pt: 'Filipinas' }],
  },
  {
    id: 'char-gui',
    hanzi: '圭', pinyin: 'guī', tone: 1,
    category: 'nome-proprio', categoryLabel: 'Caractere fonético · 1º tom',
    translation: '(fonético) em 乌拉圭 (Uruguai); tábua de jade',
    fcTranslation: '(fon.) em 乌拉圭',
    mnemonic: 'Som "gui" em 乌拉圭 (Uruguai), 巴拉圭 (Paraguai).',
    examples: [{ zh: '乌拉圭', pt: 'Uruguai' }],
  },
  {
    id: 'char-a',
    hanzi: '阿', pinyin: 'ā', tone: 1,
    category: 'nome-proprio', categoryLabel: 'Caractere fonético · 1º tom',
    translation: '(fonético/prefixo de nomes)',
    fcTranslation: '(fon.) prefixo de nomes',
    mnemonic: 'Som "a" em 阿根廷 (Argentina), 阿拉伯 (árabe).',
    examples: [{ zh: '阿根廷', pt: 'Argentina' }],
  },
  {
    id: 'char-e',
    hanzi: '俄', pinyin: 'é', tone: 2,
    category: 'nome-proprio', categoryLabel: 'Nome próprio · 2º tom',
    translation: 'Rússia (俄罗斯); repentino',
    fcTranslation: 'Rússia',
    mnemonic: '俄语 = russo; 俄罗斯 = Rússia.',
    examples: [{ zh: '俄罗斯', pt: 'Rússia' }],
  },
  {
    id: 'char-si',
    hanzi: '斯', pinyin: 'sī', tone: 1,
    category: 'nome-proprio', categoryLabel: 'Caractere fonético · 1º tom',
    translation: '(fonético) em transliterações; este (literário)',
    fcTranslation: '(fon.) em transliterações',
    mnemonic: 'Som "si/s" em 俄罗斯 (Rússia), 斯坦 (-stão).',
    examples: [{ zh: '俄罗斯', pt: 'Rússia' }],
  },
  {
    id: 'char-yi-phon',
    hanzi: '伊', pinyin: 'yī', tone: 1,
    category: 'nome-proprio', categoryLabel: 'Caractere fonético · 1º tom',
    translation: '(fonético) em 伊拉克/伊朗; ele/ela (literário)',
    fcTranslation: '(fon.) em 伊拉克',
    mnemonic: 'Som "yi" em 伊拉克 (Iraque), 伊朗 (Irã).',
    examples: [{ zh: '伊拉克', pt: 'Iraque' }],
  },
  {
    id: 'char-sa',
    hanzi: '萨', pinyin: 'sà', tone: 4,
    category: 'nome-proprio', categoryLabel: 'Caractere fonético · 4º tom',
    translation: '(fonético) em transliterações',
    fcTranslation: '(fon.) em transliterações',
    mnemonic: 'Som "sa" em 哈萨克斯坦 (Cazaquistão), 萨尔瓦多.',
    examples: [{ zh: '哈萨克斯坦', pt: 'Cazaquistão' }],
  },
  {
    id: 'char-zi',
    hanzi: '兹', pinyin: 'zī', tone: 1,
    category: 'nome-proprio', categoryLabel: 'Caractere fonético · 1º tom',
    translation: '(fonético) em 乌兹别克斯坦; agora (literário)',
    fcTranslation: '(fon.) em 乌兹别克斯坦',
    mnemonic: 'Som "zi" em 乌兹别克斯坦 (Uzbequistão).',
    examples: [{ zh: '乌兹别克斯坦', pt: 'Uzbequistão' }],
  },

  ...countryList.map(c => ({
    id: c.id,
    hanzi: c.hanzi,
    pinyin: c.pinyin,
    tone: 0,
    category: 'pais',
    categoryLabel: 'País',
    translation: c.name,
    fcTranslation: c.name,
  })),
];
