export const categories = [
  { id: 'all', label: 'Todos' },
  {
    id: 'pronome', label: 'Pronomes',
    guideTitle: 'Pronomes Pessoais',
    guideTip: '💡 <strong>Padrão visual:</strong> 我 (eu), 你 (você), 他 (ele) e 她 (ela) têm pinyin idêntico entre ele/ela — <em>tā</em>. A diferença está no radical: 他 tem 亻(pessoa) e 她 tem 女 (mulher). Adicione 们 a qualquer um para pluralizar: 我们, 你们, 他们.',
    guideLastCol: 'Dica mnemônica',
  },
  {
    id: 'verbo', label: 'Verbos',
    guideTitle: 'Verbos Essenciais',
    guideTip: '💡 <strong>是 vs 叫:</strong> ambos identificam, mas 是 é mais genérico ("sou brasileiro") e 叫 é específico para nome/apelido ("me chamo João"). 说 + idioma = falar aquele idioma.',
    guideLastCol: 'Dica mnemônica',
  },
  {
    id: 'adverbio', label: 'Advérbios',
    guideTitle: 'Advérbios e Negação',
    guideTip: '💡 <strong>Ordem importa:</strong> estes advérbios sempre ficam <em>antes do verbo</em>. Memorize a frase: 我也都还只不想去 — "Eu também, todos, ainda, apenas não quero ir." (artificial, mas cobre os 5!)',
    guideLastCol: 'Exemplo rápido',
  },
  {
    id: 'particula', label: 'Partículas',
    guideTitle: 'Partículas Gramaticais',
    guideTip: '💡 <strong>Sempre no final da frase.</strong> 吗 transforma qualquer afirmação em pergunta sim/não. 呢 pede confirmação ou continua o raciocínio — equivale a "e você?" quando dito sozinho após uma pergunta respondida.',
    guideLastCol: 'Uso',
  },
  {
    id: 'substantivo', label: 'Substantivos',
    guideTitle: 'Identidade e Nacionalidade',
    guideTip: '💡 <strong>Padrão de construção:</strong> [país] + 人 = nacionalidade | [país] + 语/文 = idioma. Ex: 中国 → 中国人 (chinês/a) → 中文 ou 汉语 (mandarim). 贵姓 ("honrado sobrenome") é a forma ultra-formal de perguntar o sobrenome.',
    guideLastCol: 'Dica',
  },
  {
    id: 'lingua', label: 'Língua',
    guideTitle: 'Língua e Cultura',
    guideTip: '💡 <strong>语 vs 文:</strong> 语 enfatiza a língua <em>falada</em> (中文 = sistema escrito; 汉语 = idioma chinês falado). 文 abrange escrita, literatura e cultura. Na prática, para "falar português" você pode dizer 说葡萄牙语.',
    guideLastCol: 'Dica',
  },
  {
    id: 'interrogativo', label: 'Interrogativos',
    guideTitle: 'Interrogativos',
    guideTip: '💡 <strong>什 e 么 raramente aparecem sozinhos.</strong> O par 什么 significa "o quê?" e é um dos interrogativos mais frequentes do mandarim. Em composição: 为什么 (por quê?), 什么时候 (quando?), 怎么 (como?). 哪 (nǎ) = qual/onde.',
    guideLastCol: 'Contexto',
  },
  { id: 'conectivo', label: 'Conectivos' },
];

export const hanziList = [
  // ── PRONOMES ──────────────────────────────────────────────────
  {
    id: 'wo',
    hanzi: '我', pinyin: 'wǒ', tone: 3,
    category: 'pronome', categoryLabel: 'Pronome · 3º tom',
    translation: 'eu, me, mim',
    fcTranslation: 'eu · me · mim',
    mnemonic: 'Imagine uma mão (手) apontando para si mesmo — é justamente o que "eu" faz.',
    examples: [{ zh: '我是巴西人。', pt: 'Sou brasileiro/a.' }],
  },
  {
    id: 'ni',
    hanzi: '你', pinyin: 'nǐ', tone: 3,
    category: 'pronome', categoryLabel: 'Pronome · 3º tom',
    translation: 'você',
    mnemonic: 'Radical 亻(pessoa) + 尔. Você é uma <em>pessoa</em> bem próxima de mim.',
    examples: [{ zh: '你好！', pt: 'Olá! (lit. você bem!)' }],
  },
  {
    id: 'nin',
    hanzi: '您', pinyin: 'nín', tone: 2,
    category: 'pronome', categoryLabel: 'Pronome formal · 2º tom',
    translation: 'o senhor / a senhora (formal)',
    fcTranslation: 'o senhor · a senhora',
    mnemonic: 'É 你 com um coração (心) embaixo — respeito que vem do coração.',
    examples: [{ zh: '您好！', pt: 'Olá (formal)' }],
  },
  {
    id: 'ta-m',
    hanzi: '他', pinyin: 'tā', tone: 1,
    category: 'pronome', categoryLabel: 'Pronome · 1º tom',
    translation: 'ele',
    mnemonic: 'Radical 亻(pessoa) + 也. Uma pessoa <em>também</em> presente = ele.',
    examples: [{ zh: '他是学生。', pt: 'Ele é estudante.' }],
  },
  {
    id: 'ta-f',
    hanzi: '她', pinyin: 'tā', tone: 1,
    category: 'pronome', categoryLabel: 'Pronome · 1º tom',
    translation: 'ela',
    mnemonic: 'Radical 女 (mulher) deixa clara a distinção de 他.',
    examples: [{ zh: '她也是学生。', pt: 'Ela também é estudante.' }],
  },
  {
    id: 'men',
    hanzi: '们', pinyin: 'men', tone: 0,
    category: 'pronome', categoryLabel: 'Sufixo · tom neutro',
    translation: 'sufixo de plural para pessoas',
    fcTranslation: 'sufixo de plural',
    mnemonic: 'Radical 亻(pessoa) + 门 (porta). Muitas pessoas passando pela mesma porta = plural.',
    examples: [{ zh: '我们 · 你们 · 他们', pt: '' }],
  },

  // ── VERBOS ────────────────────────────────────────────────────
  {
    id: 'shi',
    hanzi: '是', pinyin: 'shì', tone: 4,
    category: 'verbo', categoryLabel: 'Verbo · 4º tom',
    translation: 'ser; estar; é',
    fcTranslation: 'ser · estar · é',
    mnemonic: 'Um dos caracteres mais usados. O radical 日 (sol) + 疋 — "o que é" está à luz do sol, exposto.',
    examples: [{ zh: '我是中国人。', pt: 'Sou chinês/a.' }],
  },
  {
    id: 'jiao',
    hanzi: '叫', pinyin: 'jiào', tone: 4,
    category: 'verbo', categoryLabel: 'Verbo · 4º tom',
    translation: 'chamar-se; chamar; gritar',
    fcTranslation: 'chamar-se · chamar',
    mnemonic: 'Radical 口 (boca) + 丩. Usar a boca para chamar alguém pelo nome.',
    examples: [{ zh: '我叫王芳。', pt: 'Me chamo Wang Fang.' }],
  },
  {
    id: 'shuo',
    hanzi: '说', pinyin: 'shuō', tone: 1,
    category: 'verbo', categoryLabel: 'Verbo · 1º tom',
    translation: 'falar; dizer',
    fcTranslation: 'falar · dizer',
    mnemonic: 'Radical 讠(fala) + 兑. O radical da fala é pista imediata: ação vocal.',
    examples: [{ zh: '你说中文吗？', pt: 'Você fala chinês?' }],
  },

  // ── ADVÉRBIOS ─────────────────────────────────────────────────
  {
    id: 'ye',
    hanzi: '也', pinyin: 'yě', tone: 3,
    category: 'adverbio', categoryLabel: 'Advérbio · 3º tom',
    translation: 'também',
    mnemonic: '我也是 — Eu também sou.',
    examples: [{ zh: '我也是学生。', pt: 'Eu também sou estudante.' }],
  },
  {
    id: 'dou',
    hanzi: '都', pinyin: 'dōu', tone: 1,
    category: 'adverbio', categoryLabel: 'Advérbio · 1º tom',
    translation: 'todos; ambos; tudo',
    fcTranslation: 'todos · ambos · tudo',
    mnemonic: '我们都是 — Nós todos somos.',
    examples: [{ zh: '我们都是学生。', pt: 'Somos todos estudantes.' }],
  },
  {
    id: 'zhi',
    hanzi: '只', pinyin: 'zhǐ', tone: 3,
    category: 'adverbio', categoryLabel: 'Advérbio · 3º tom',
    translation: 'só; apenas',
    fcTranslation: 'só · apenas',
    mnemonic: '我只说中文 — Eu só falo chinês.',
    examples: [{ zh: '我只说中文。', pt: 'Só falo chinês.' }],
  },
  {
    id: 'hai',
    hanzi: '还', pinyin: 'hái', tone: 2,
    category: 'adverbio', categoryLabel: 'Advérbio · 2º tom',
    translation: 'ainda; também (além disso)',
    fcTranslation: 'ainda · também (além disso)',
    mnemonic: '他还是学生 — Ele ainda é estudante.',
    examples: [{ zh: '他还是学生。', pt: 'Ele ainda é estudante.' }],
  },
  {
    id: 'bu',
    hanzi: '不', pinyin: 'bù', tone: 4,
    category: 'adverbio', categoryLabel: 'Negação · 4º / 2º tom',
    translation: 'não',
    mnemonic: '我不是 — Eu não sou. (Vira 2º tom antes de outro 4º tom: 不是 → bú shì)',
    examples: [{ zh: '我不是学生。', pt: 'Não sou estudante.' }],
  },

  // ── PARTÍCULAS ────────────────────────────────────────────────
  {
    id: 'ma',
    hanzi: '吗', pinyin: 'ma', tone: 0,
    category: 'particula', categoryLabel: 'Partícula · tom neutro',
    translation: 'partícula de pergunta sim/não',
    mnemonic: '你是学生吗？— Você é estudante?',
    examples: [{ zh: '你是学生吗？', pt: 'Você é estudante?' }],
  },
  {
    id: 'ne',
    hanzi: '呢', pinyin: 'ne', tone: 0,
    category: 'particula', categoryLabel: 'Partícula · tom neutro',
    translation: 'partícula de continuação/confirmação',
    fcTranslation: 'e você? · e quanto a...?',
    mnemonic: '你呢？— E você? / Que tal você?',
    examples: [{ zh: '你呢？', pt: 'E você?' }],
  },

  // ── SUBSTANTIVOS (Identidade) ─────────────────────────────────
  {
    id: 'xing',
    hanzi: '姓', pinyin: 'xìng', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º tom',
    translation: 'sobrenome; chamar-se (sobrenome)',
    fcTranslation: 'sobrenome',
    mnemonic: 'Radical 女 (mulher) + 生 (nascer). Sobrenome é o nome de nascença matrilinear.',
    examples: [{ zh: '您贵姓？', pt: 'Qual é seu sobrenome? (formal)' }],
  },
  {
    id: 'ming',
    hanzi: '名', pinyin: 'míng', tone: 2,
    category: 'substantivo', categoryLabel: 'Substantivo · 2º tom',
    translation: 'nome (dado); fama; famoso',
    fcTranslation: 'nome · fama',
    mnemonic: '夕 (noite) + 口 (boca). À noite, você grita um nome para identificar alguém no escuro.',
    examples: [{ zh: '你叫什么名字？', pt: 'Qual é seu nome?' }],
  },
  {
    id: 'zi',
    hanzi: '字', pinyin: 'zì', tone: 4,
    category: 'substantivo', categoryLabel: 'Substantivo · 4º tom',
    translation: 'caractere; palavra escrita; nome de cortesia',
    fcTranslation: 'caractere · palavra escrita',
    mnemonic: '子 (filho) sob um teto 宀 = a escrita nasce e é abrigada.',
    examples: [{ zh: '汉字 (hànzì) = caracteres chineses', pt: '' }],
  },
  {
    id: 'guo',
    hanzi: '国', pinyin: 'guó', tone: 2,
    category: 'substantivo', categoryLabel: 'Substantivo · 2º tom',
    translation: 'país; nação',
    fcTranslation: 'país · nação',
    mnemonic: 'Um território (口 grande) guardado por fronteiras com jade (玉) no centro — o tesouro da nação.',
    examples: [{ zh: '中国 · 英国 · 美国 · 巴西', pt: '' }],
  },
  {
    id: 'gui',
    hanzi: '贵', pinyin: 'guì', tone: 4,
    category: 'substantivo', categoryLabel: 'Adjetivo · 4º tom',
    translation: 'caro; nobre; honrado',
    fcTranslation: 'caro · nobre · honrado',
    mnemonic: '貝 (moeda antiga) embaixo = algo de alto valor monetário ou social.',
    examples: [{ zh: '贵姓 = honrado sobrenome (forma ultra-formal)', pt: '' }],
  },

  // ── LÍNGUA ────────────────────────────────────────────────────
  {
    id: 'yu',
    hanzi: '语', pinyin: 'yǔ', tone: 3,
    category: 'lingua', categoryLabel: 'Substantivo · 3º tom',
    translation: 'idioma; língua (falada)',
    fcTranslation: 'idioma · língua falada',
    mnemonic: 'Radical 讠(fala) — ênfase na oralidade. 英语, 汉语, 法语...',
    examples: [{ zh: '中文 / 汉语 · 英语 · 葡萄牙语', pt: '' }],
  },
  {
    id: 'wen',
    hanzi: '文', pinyin: 'wén', tone: 2,
    category: 'lingua', categoryLabel: 'Substantivo · 2º tom',
    translation: 'escrita; texto; língua; cultura',
    fcTranslation: 'escrita · texto · língua · cultura',
    mnemonic: 'Parece um ideograma de pessoa ornamentada com tatoo — cultura, arte, escrita.',
    examples: [{ zh: '中文 = chinês (língua/escrita)', pt: '' }],
  },
  {
    id: 'he',
    hanzi: '和', pinyin: 'hé', tone: 2,
    category: 'lingua', categoryLabel: 'Conjunção · 2º tom',
    translation: 'e; com; harmonia',
    fcTranslation: 'e · com · harmonia',
    mnemonic: '禾 (cereal) + 口 (boca). Compartilhar comida = harmonia, união, "e".',
    examples: [{ zh: '我和你 — Eu e você', pt: '' }],
  },

  // ── INTERROGATIVOS ────────────────────────────────────────────
  {
    id: 'na',
    hanzi: '哪', pinyin: 'nǎ', tone: 3,
    category: 'interrogativo', categoryLabel: 'Interrogativo · 3º tom',
    translation: 'qual; que; onde (em estruturas)',
    fcTranslation: 'qual · que · onde',
    mnemonic: 'Radical 口 (boca) — a boca fazendo a pergunta "qual?"',
    examples: [{ zh: '你是哪国人？', pt: 'De que país você é?' }],
  },
  {
    id: 'shen',
    hanzi: '什', pinyin: 'shén', tone: 2,
    category: 'interrogativo', categoryLabel: 'Interrogativo · 2º tom',
    translation: 'usado em 什么 (o quê?)',
    mnemonic: '你叫什么名字？— Qual é o seu nome?',
    examples: [{ zh: '什么 (shénme) = o quê? / qual?', pt: '' }],
  },
  {
    id: 'me',
    hanzi: '么', pinyin: 'me', tone: 0,
    category: 'interrogativo', categoryLabel: 'Partícula · tom neutro',
    translation: 'usado em 什么 (o quê?); 这么/那么 (assim/tão)',
    fcTranslation: 'usado em 什么 · 怎么 · 这么',
    mnemonic: 'Também em: 这么 (assim), 那么 (então/tão), 怎么 (como).',
    examples: [{ zh: '什么、这么、那么、怎么', pt: '' }],
  },
];
